// svelte/src/components/header/Header.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import { link } from 'svelte-spa-router'
  import active from 'svelte-spa-router/active'
  import { Collapse } from 'bootstrap'

  const themeKey = '001_modern_web_frameworks_svelte_theme'

  let theme = $state<'dark' | 'light'>('dark')

  const applyTheme = () => {
    document.body.setAttribute('data-bs-theme', theme)
  }

  const toggleTheme = () => {
    theme = theme === 'dark' ? 'light' : 'dark'
    localStorage.setItem(themeKey, theme)
    applyTheme()
  }

  const closeNavbar = () => {
    const navbar = document.getElementById('navbar_content')
    if (navbar?.classList.contains('show')) {
      const collapse = Collapse.getOrCreateInstance(
        navbar,
        { toggle: false }
      )
      collapse.hide()
    }
  }

  const handleThemeClick = () => {
    toggleTheme()
    closeNavbar()
  }

  onMount(() => {
    const savedTheme = localStorage.getItem(themeKey)
    theme = savedTheme === 'light' ? 'light' : 'dark'
    applyTheme()
  })
</script>

<nav class="navbar navbar-expand-sm bg-body-tertiary sticky-top">

  <div class="container-fluid">

    <!-- Hamburger -->
    <button class="navbar-toggler ms-auto"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbar_content"
            aria-controls="navbar_content"
            aria-expanded="false"
            aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Navbar content -->
    <div id="navbar_content"
         class="collapse navbar-collapse mt-3 mt-sm-0">

      <!-- LEFT -->
      <ul class="navbar-nav me-auto ms-0 ms-sm-3">

        <!-- Home -->
        <li class="nav-item mx-1">
          <a href="/"
             use:link
             use:active
             class="nav-link"
             onclick={closeNavbar}>
            <span class="text-capitalize text-small-caps">
              <i class="fa-solid fa-house me-1"></i>
              <span>Home</span>
            </span>
          </a>
        </li>

        <!-- Page1 -->
        <li class="nav-item mx-1">
          <a href="/page1"
             use:link
             use:active
             class="nav-link"
             onclick={closeNavbar}>
            <span class="text-capitalize text-small-caps">
              <i class="fa-solid fa-face-smile me-1"></i>
              <span>Page1</span>
            </span>
          </a>
        </li>

        <!-- Page2 -->
        <li class="nav-item mx-1">
          <a href="/page2"
             use:link
             use:active
             class="nav-link"
             onclick={closeNavbar}>
            <span class="text-capitalize text-small-caps">
              <i class="fa-solid fa-globe me-1"></i>
              <span>Page2</span>
            </span>
          </a>
        </li>
      </ul>

      <!-- RIGHT -->
      <ul class="navbar-nav ms-auto me-0 me-sm-3">

        <li class="nav-item mx-1">
          <button type="button"
                  class="nav-link border-0 bg-transparent"
                  onclick={handleThemeClick}
                  title="Change theme"
                  aria-label="Change theme">
            <i class="fa-solid me-1 me-sm-0"
               class:fa-sun={theme === 'dark'}
               class:fa-moon={theme === 'light'}></i>
            <span class="d-sm-none">
              Change theme
            </span>
          </button>
        </li>
      </ul>
    </div>
  </div>
</nav>

<style>
  nav :global(.nav-link.active) {
    text-decoration: underline;
    pointer-events: none;
  }
</style>

// react/src/components/header/Header.tsx
import { useEffect, useState } from 'react'
import { NavLink } from 'react-router'
import { Collapse } from 'bootstrap'

import styles from './Header.module.css'

function Header() {

  const themeKey = '001_modern_web_frameworks_react_theme'

  const [theme, setTheme] = useState<'dark' | 'light'>(() => {
    const savedTheme = localStorage.getItem(themeKey)
    return savedTheme === 'light' ? 'light' : 'dark'
  })

  useEffect(() => {
    document.body.setAttribute('data-bs-theme', theme)
    localStorage.setItem(themeKey, theme)
  }, [theme])

  // Toggle theme
  const toggleTheme = () => {
    setTheme(theme === 'dark' ? 'light' : 'dark')
  }

  // Close navbar
  const closeNavbar = () => {
    const navbar = document.getElementById('navbar_content')
    if (navbar?.classList.contains('show')) {
      const collapse = Collapse.getOrCreateInstance(navbar, { toggle: false })
      collapse.hide()
    }
  }

  return (
    <nav className="navbar navbar-expand-sm bg-body-tertiary sticky-top">

      <div className="container-fluid">

        {/* Hamburger */}
        <button className="navbar-toggler ms-auto"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbar_content"
                aria-controls="navbar_content"
                aria-expanded="false"
                aria-label="Toggle navigation">
          <span className="navbar-toggler-icon"></span>
        </button>

        {/* Navbar content */}
        <div id="navbar_content"
             className="collapse navbar-collapse mt-3 mt-sm-0">

          {/* LEFT */}
          <ul className="navbar-nav me-auto ms-0 ms-sm-3">

            {/* Home */}
            <li className="nav-item mx-1">
              <NavLink to="/"
                       end
                       className={({ isActive }) => `nav-link 
                                ${isActive ? styles.navItemActive : ''}`}
                       onClick={closeNavbar}>
                <span className="text-capitalize text-small-caps">
                  <i className="fa-solid fa-house me-1"></i>
                  <span>Home</span>
                </span>
              </NavLink>
            </li>

            {/* Page1 */}
            <li className="nav-item mx-1">
              <NavLink to="/page1"
                       className={({ isActive }) => `nav-link 
                                ${isActive ? styles.navItemActive : ''}`}
                       onClick={closeNavbar}>
                <span className="text-capitalize text-small-caps">
                  <i className="fa-solid fa-face-smile me-1"></i>
                  <span>Page1</span>
                </span>
              </NavLink>
            </li>

            {/* Page2 */}
            <li className="nav-item mx-1">
              <NavLink to="/page2"
                       className={({ isActive }) => `nav-link 
                                ${isActive ? styles.navItemActive : ''}`}
                       onClick={closeNavbar}>
                <span className="text-capitalize text-small-caps">
                  <i className="fa-solid fa-globe me-1"></i>
                  <span>Page2</span>
                </span>
              </NavLink>
            </li>
          </ul>

          {/* RIGHT */}
          <ul className="navbar-nav ms-auto me-0 me-sm-3">

            {/* Theme */}
            <li className="nav-item mx-1">
              <button type="button"
                      className="nav-link border-0 bg-transparent"
                      onClick={() => {
                        toggleTheme()
                        closeNavbar()
                      }}
                      title="Change theme"
                      aria-label="Change theme">
                <i className={`fa-solid me-1 me-sm-0 
                            ${theme === 'dark' ? 'fa-sun' : 'fa-moon'}`}></i>
                <span className="d-sm-none">
                  Change theme
                </span>
              </button>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  )
}

export default Header
